Luzin fixes
misterkrull/Shpargalkees pull request #1
Opened 2024-07-03 18:45 UTC by Arjunarus

Внес точечные правки там где явные косяки. Остальное в комментариях.

2024-07-09 16:34 UTC, misterkrull commented on git_commands.txt
> +git add	.		Заиндексировать всю текущую папку
Т.е. если в репозитории есть какая-то другая папка, в которую перейти (через cd) и там сделать "git add .", то заиндексируется только она? 
Но если текущая папка корневая, то "git add ." == "git add -A"?

2024-07-09 16:38 UTC, Arjunarus commented on git_commands.txt
> +git add --all	То же что -A
тут поехала табуляция, чтобы такого не происходило рекомендую настроить редактор чтобы он вместо tab-ов пробелы вставлял. Из-за табов в тексте часто все едет всрато.

2024-07-09 16:38 UTC, Arjunarus commented on git_commands.txt
> +git add	.		Заиндексировать всю текущую папку
Да все верно. Точка в шелле обозначает текущую папку, это даже не к гиту относится.

2024-07-09 16:45 UTC, misterkrull commented on git_commands.txt
> +git add --all	То же что -A
Я в Блокноте делал. Там нет настроек xD Да и не нужны для такого моего личного проекта)))

Ну и вроде у тебя табуляция поехала из-за того, что ты один таб удалил... ну, гит отмечает удаление одного таба

2024-07-09 16:50 UTC, Arjunarus commented on git_commands.txt
> +git add --all	То же что -A
ну это я в общем говорю, ну и чтобы коммент был повод оставить ) 
в notepad++ там есть такая настройка

2024-07-09 16:55 UTC, Arjunarus commented on git_commands.txt
> +git add --all	То же что -A
поставил табулятор, теперь норм. Еще тут оказывается комменты привязаны к изменениям, то есть можно отедльно по коммитам комментить.

2024-07-09 16:58 UTC, misterkrull commented on git_commands.txt
>  Главное в туториалах по rebase — не делайте этого с комитами, доступными не только вам.
коММитами блджад

2024-07-09 16:59 UTC, Arjunarus commented on git_commands.txt
>  Главное в туториалах по rebase — не делайте этого с комитами, доступными не только вам.
ага увидел ) 
реклама comet вспомнилась

2024-07-09 17:19 UTC, misterkrull approved these changes

2024-07-09 18:23 UTC, misterkrull commented on git_commands.txt
> +git checkout <commit hash>	Перевод состояния файлов к определённому коммиту (указывается либо его хэш либо любой иной указатель на этот коммит, если есть)
Ну да, так сказать более грамотно :)) Хотя "откат" тоже сюда подходит, но версия с "откатом" не настолько однозначна :)

2024-07-09 18:24 UTC, misterkrull commented on git_commands.txt
> +				Если начать коммитить отсюда, то получится "ветка" которая никак не называется, просто будет болтающийся сбоку коммит.
Но ведь эту ветку можно будет как-то обозвать?

2024-07-09 18:25 UTC, misterkrull commented on git_commands.txt
> -				При этом типа правится история и типа так лучше не делать
История при этом вообще не правится? 
История правится при ребейзе, да? и вот ребейз лучше не делать, да?

2024-07-09 18:25 UTC, misterkrull commented on git_commands.txt
> -				При этом типа правится история и типа так лучше не делать
ребейз нужен, только если откровенный партак убрать? :))))))))

2024-07-09 18:35 UTC, misterkrull requested changes
чё-та написал сюда :)

отменяю аппрув, ставлю реквест чейнджес, чтобы посмотреть, чё получится)))

2024-07-09 18:35 UTC, misterkrull commented on git_commands.txt
> -				При этом типа правится история и типа так лучше не делать
просто коммент, чтобы посмотреть функцию Start a review

2024-07-09 18:35 UTC, misterkrull commented on git_commands.txt
> -				При этом типа правится история и типа так лучше не делать
Ага, у меня уже один коммент добавлен в мой ревью
Вернее даже ревью создан
Теперь пропала кнопка Add single comment, а кнопка Start a review заменилась на Add review comment

2024-07-09 18:35 UTC, misterkrull commented on git_commands.txt
> -				При этом типа правится история и типа так лучше не делать
Просто третий коммент
Б-г любит т-цу

2024-07-11 13:35 UTC, merged

2024-07-11 13:42 UTC, misterkrull reviewed
А теперь попробую уже после слияния таки одобрить пулреквест :)